# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spot2mp3.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(930, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(340, 0, 270, 41))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("")
        self.title_label.setText("Spotify2Apple")
        self.title_label.setObjectName("title_label")
        self.enter_playlist_url_label = QtWidgets.QLabel(self.centralwidget)
        self.enter_playlist_url_label.setGeometry(QtCore.QRect(140, 358, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.enter_playlist_url_label.setFont(font)
        self.enter_playlist_url_label.setObjectName("enter_playlist_url_label")
        self.url_input = QtWidgets.QLineEdit(self.centralwidget)
        self.url_input.setGeometry(QtCore.QRect(140, 379, 550, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.url_input.setFont(font)
        self.url_input.setStyleSheet("color: rgb(240, 240, 240)")
        self.url_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.url_input.setObjectName("url_input")
        self.url_load_button = QtWidgets.QPushButton(self.centralwidget)
        self.url_load_button.setGeometry(QtCore.QRect(40, 378, 90, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.url_load_button.setFont(font)
        self.url_load_button.setObjectName("url_load_button")
        self.remove_from_table_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_from_table_button.setGeometry(QtCore.QRect(730, 350, 150, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.remove_from_table_button.setFont(font)
        self.remove_from_table_button.setObjectName("remove_from_table_button")
        self.url_error_label = QtWidgets.QLabel(self.centralwidget)
        self.url_error_label.setGeometry(QtCore.QRect(525, 360, 170, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.url_error_label.setFont(font)
        self.url_error_label.setObjectName("url_error_label")
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setGeometry(QtCore.QRect(40, 430, 110, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.download_button.setFont(font)
        self.download_button.setObjectName("download_button")
        self.video_table = QtWidgets.QTableWidget(self.centralwidget)
        self.video_table.setGeometry(QtCore.QRect(30, 60, 871, 284))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.video_table.setFont(font)
        self.video_table.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.video_table.setStyleSheet("color: rgb(240, 240, 240)")
        self.video_table.setMidLineWidth(0)
        self.video_table.setRowCount(300)
        self.video_table.setColumnCount(5)
        self.video_table.setObjectName("video_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        item.setFont(font)
        self.video_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        item.setFont(font)
        self.video_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        item.setFont(font)
        self.video_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        item.setFont(font)
        self.video_table.setHorizontalHeaderItem(4, item)
        self.video_table.horizontalHeader().setVisible(True)
        self.video_table.horizontalHeader().setCascadingSectionResizes(False)
        self.video_table.horizontalHeader().setDefaultSectionSize(164)
        self.video_table.horizontalHeader().setMinimumSectionSize(19)
        self.video_table.verticalHeader().setCascadingSectionResizes(False)
        self.video_table.verticalHeader().setDefaultSectionSize(34)
        self.video_table.verticalHeader().setHighlightSections(True)
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(160, 430, 110, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.album_artwork = QtWidgets.QLabel(self.centralwidget)
        self.album_artwork.setGeometry(QtCore.QRect(710, 390, 201, 201))
        self.album_artwork.setStyleSheet("background-color: rgb(82, 95, 106)")
        self.album_artwork.setFrameShape(QtWidgets.QFrame.Panel)
        self.album_artwork.setFrameShadow(QtWidgets.QFrame.Plain)
        self.album_artwork.setText("")
        self.album_artwork.setPixmap(QtGui.QPixmap("../../YouTube2Audio/img/default_artwork.png"))
        self.album_artwork.setScaledContents(True)
        self.album_artwork.setAlignment(QtCore.Qt.AlignCenter)
        self.album_artwork.setObjectName("album_artwork")
        self.download_status = QtWidgets.QLabel(self.centralwidget)
        self.download_status.setGeometry(QtCore.QRect(50, 490, 361, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.download_status.setFont(font)
        self.download_status.setText("")
        self.download_status.setObjectName("download_status")
        self.credit_url = QtWidgets.QLabel(self.centralwidget)
        self.credit_url.setGeometry(QtCore.QRect(440, 40, 80, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.credit_url.setFont(font)
        self.credit_url.setObjectName("credit_url")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 930, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube to Audio"))
        self.enter_playlist_url_label.setText(_translate("MainWindow", "Playlist URL"))
        self.url_load_button.setText(_translate("MainWindow", "Load"))
        self.remove_from_table_button.setText(_translate("MainWindow", "Remove Song"))
        self.url_error_label.setText(_translate("MainWindow", "Could not load URL. Try again."))
        self.download_button.setText(_translate("MainWindow", "Download"))
        self.video_table.setSortingEnabled(False)
        item = self.video_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Song"))
        item = self.video_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Artist"))
        item = self.video_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Album"))
        item = self.video_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Album Artist"))
        item = self.video_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Artwork"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.credit_url.setText(_translate("MainWindow", "source code"))
